name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_patter: "feat:"
        version_format: "${major}.${minor}.${patch}.${increment}"
        # version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version}}
      run:  |
        echo "New Version👉 $NEW_VERSION"
    #     echo "Initialize login"
    #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    #     echo "Finish login"
    # - name: Build Docker Image
    #   run: |
    #     docker build -t moive30/docker-graphql:0.0.2 .
    #     docker build -t moive30/docker-graphql:latest .
    # - name: Push Docker Image
    #   run: |
    #     docker push moive30/docker-graphql:0.0.2
    #     docker push moive30/docker-graphql:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
